volumes:
  data: {}

services:
  postgresql:
    container_name: postgresql
    image: postgres:12
    environment:
      POSTGRES_DB: 'admin'
      POSTGRES_USER: 'password'
      POSTGRES_PASSWORD: 'demo_catalog'
    ports:
      - "6543:6543"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 3

  minio:
    container_name: minio
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data:/data
    command: server /data --console-address ":9001"

  create-bucket:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - data:/data
    entrypoint: mc mb /data/bucket

  rest:
    hostname: irc
    image: apache/iceberg-rest-fixture:1.8.1
    depends_on:
      postgresql:
        condition: service_healthy
      minio:
        condition: service_started
    volumes:
      - ./postgresql-42.7.5.jar:/usr/lib/iceberg-rest/postgresql-42.7.5.jar
    ports:
      - "8181:8181"
    environment:
      CATALOG_URI: jdbc:postgresql://postgresql:6543/demo_catalog
      CATALOG_JDBC_USER: admin
      CATALOG_JDBC_PASSWORD: password

      AWS_REGION: us-east-1
      CATALOG_WAREHOUSE: s3://bucket/warehouse/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: http://minio:9000
      CATALOG_S3_PATH__STYLE__ACCESS: true
      CATALOG_S3_ACCESS__KEY__ID: admin
      CATALOG_S3_SECRET__ACCESS__KEY: password

    command: java -cp /usr/lib/iceberg-rest/*:iceberg-rest-adapter.jar org.apache.iceberg.rest.RESTCatalogServer

  trino:
    container_name: trino
    image: trinodb/trino
    environment:
      CATALOG_MANAGEMENT: 'dynamic'
    depends_on:
      - rest
      - minio
    ports:
      - "8080:8080"